### ISSUE TITLE
Add support for running server on a cloud platform

### ISSUE THREAD

**Issue by AlexWang-16** [AlexWang-16/webservice-phonelibrary#8]

**Comment by mkavidas** [comment]
Was kind of unsure what this meant but I setup a remote on Heroku so now you can access the app at:

https://webservice-phonelibrary.herokuapp.com/

**Comment by AlexWang-16** [comment]
Hey @mkavidas, thanks for setting up the web service on Heroku. This is exactly what I was expecting and it works flawlessly!
